msgpack/msgpack-javascript

msgpack.codec.js
msgpack.js
test/codec.htm

https://github.com/msgpack/msgpack/blob/master/spec.md#bin-format-family

Added bin format family support.

---

src/encode.ts
src/utils/WritableBuffer.ts
tsconfig.json
tsconfig.production.json

This has some performance penalty but better than `Uint8Aray.from(encode(obj))`.

Make encode() return Uint8Array

---

src/Decoder.ts
src/Encoder.ts
src/ExtensionCodec.ts
src/utils/int.ts
test/codec-int.test.ts

To use DataView heavily and reduce the code.

refine int64 handling

---

README.md
src/Decoder.ts
src/decode.ts
src/decodeAsync.ts
test/decode-max-length.test.ts

Inspired in msgpack-python: https://msgpack-python.readthedocs.io/en/latest/api.html
Each default is UINT32_MAX and users do not need to configure them if the input is trusted.

implement maxStrLength/maxBinLen/maxArrayLen/maxMapLen/maxExtLen options to safely decode untrusted bytes

---

src/Encoder.ts

To reduce `Object.keys()` not to affect GC.

reduce array allocation in encoding maps

---

src/Decoder.ts

Hi @gfx I've used this msgpack library in my project and found small optimization that improves decoding speed by 3-4%.

Improve array decoding performance

---

src/utils/utf8.ts

@gfx here is string decoding optimization PR

Optimize string decoding performance

---

.travis.yml

Travis CI logs said:
> Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
Setting environment variables from .travis.yml

Fix CI secrets to run tests for Sauce Labs

---

README.md
package-lock.json
package.json
src/index.ts
src/timestamp.ts
test/readme.test.ts

Also added an example to re-map timestamp-ext with [@std-proposal/temporal](https://github.com/std-proposal/temporal).

add decodeTimestampToTimeSpec() to register custom timestamp ext handlers

---

src/decodeAsync.ts
src/utils/stream.ts
test/readme.test.ts
test/whatwg-streams.test.ts

whatwg-streams are standard stream api in browsers, for example as the response body of whatwg fetch api. Unfortunately, whatwg-streams do not support `AsyncIterable`, so if you want to give them to `decodeAsync()` you have to convert them to `AsyncIterable`, which is not a trivial thing.
---
This PR is working in progress, waiting for #42 is merged.

support whatwg-stream.ReadableStream as decodeAsync() input source

---

src/index.ts

In some cases Decoder/Encoder need to be used directly without wrapper functions. For example in our project we have custom format that consist of 
binary with:
- number
- number
- array 
- number
- binary
and this structure can't be parsed or formed using regular functions, but it can be easily done by using Decoder/Encoder directly.

Export Decoder and Encoder for direct usage

---

test/decodeArrayStream.test.ts

@gfx just few of basic tests for decodeArrayStream #42

Add basic tests for decodeArrayStream

---

CHANGELOG.md
README.md

I'm thinking about whether or not I should make pull-requests for each release 🤔

releng for v1.3.0

---

.travis.yml
package.json
sauceLabs.ts
test/whatwg-streams.test.ts

Fix https://travis-ci.org/msgpack/msgpack-javascript/jobs/539247973
> Edge 18.17763.0 (Windows 10.0.0) whatwg streams decodeAsync FAILED
> 	TypeError: Function expected
> 	   at Anonymous function (webpack:///test/whatwg-streams.test.ts:14:10 <- test/karma-run.js:26328:21)
This PR also fixes codecov settings and now it gets sane.

fix tests on Edge for ReadableStream

---

README.md
src/Decoder.ts
src/decode.ts
src/decodeAsync.ts

In readme, `decodeStream(stream: AsyncIterable<Uint8Array | ArrayLike<number>> | ReadableStream<Uint8Array | ArrayLike<number>>, options?: DecodeAsyncOptions): AsyncIterable<unknown>` is too complex to read.
Because `Uint8Array` includes `ArrayLike<number>`, `Uint8Array | ArrayLike<number>` can be simplified  to `ArrayLike<number>`.

simplify type of decode()'s first arg; ArrayLike<number> includes Uint8Array, anyway

---

.travis.yml

To ensure to support multiple nodejs versions, introduce the `matrix.include` section.
https://docs.travis-ci.com/user/build-matrix/

CI: add nodejs versions to the matrix

---

README.md
src/Encoder.ts
src/encode.ts
test/encode-options.test.ts

* https://github.com/mcollina/msgpack5 has the same option `sortKeys`
* msgpack-lite has pull request https://github.com/kawanet/msgpack-lite/pull/103 has a pull-request for canonical encoding

Support canonical encoding by adding sortKeys option to encode()

---

src/Encoder.ts
test/msgpack-test-suite.test.ts

fix RangeError in encoding BLOB

---

package-lock.json
package.json
src/utils/stream.ts
test/whatwg-streams.test.ts

`object instanceof ReadableStream` does not allow ponyfills, a clone of built-in class, so it takes other ways.
In addition, this PR also supports a newer feature`ReadableStream.prototype[@@asyncIterator]`, which is supported by no browser as of June 2019.

allow stream ponyfill as ReadableStream

---

README.md
example/amd-example.html
example/amd-example.js
webpack.config.ts

* use the name `MessagePack` for AMD
* Remove all the nodejs `process` global objects
Now `<script src="https://unpkg.com/@msgpack/msgpack"></script>` loads `MessagePack` as its module.

fix AMD-style modules; add amd-example.html for testing

---

src/Encoder.ts
test/msgpack-test-suite.test.ts

pointed out by https://github.com/msgpack/website/pull/19
This is a long existing bug coming from the classic version of msgpack-javascript

fix int8 range in encoding

---

README.md
src/Encoder.ts
src/encode.ts
test/encode.test.ts

If the double precision is not required, float32 is more compact than float64.
It is useful if the precisions of numbers do not matter.

implement `forceFloat32` to encode numbers in float32 instead of float64

---

src/Decoder.ts
src/decode.ts
src/decodeAsync.ts

refactor: merge internal decodeStream and decodeArrayStream into decodeMultiAsync

---

src/utils/utf8.ts

Hi,
I noticed when I passed very long strings to decode it would crash out with `RangeError: Maximum call stack size exceeded.`. The code seemingly already protects against this with `CHUNK_SIZE` but allows it to go over by 4 items due to the `- 4` (unclear why this exists). Removing the `-4` stops this crash.

if you exceed CHUNK_SIZE safari will crash with a range error

---

src/utils/utf8.ts

Hi,
Sorry to touch this same area again! Turns out my previous fix wasn't enough for most use cases. In isolation reducing it by `4` was enough to pass tests but if your code is running on any kind of stack itself you'll run out of stack space. Looking at what some other projects do it seems pretty popular to just change this value to give yourself some headroom (like: https://github.com/feross/buffer/blob/master/index.js#L1023)

protect stack size even further

---

.mocharc.js
test/mocha.opts

Because `mocha.opts` is deprecated in Mocha 7.
https://mochajs.org/#configuring-mocha-nodejs

Migration to .mocharc.js from mocha.opts

---

src/decodeAsync.ts
src/index.ts

export EncodeOptions and DecodeOptions 

---

README.md
src/Decoder.ts
src/Encoder.ts
src/ExtensionCodec.ts
src/context.ts
src/decode.ts
src/decodeAsync.ts
src/encode.ts
test/ExtensionCodec.test.ts

Added support for custom context for keeping track of objects

---

README.md
src/Encoder.ts
src/encode.ts
test/encode.test.ts

Resolve https://github.com/msgpack/msgpack-javascript/issues/106

add EncodeOptions#ignoreUndefined to ignore undefined values in maps

---

README.md

Seems like this should be "decode" instead of "encode" in the decode example

Correct an import from "encode" to "decode"

---

.eslintrc.js
README.md
benchmark/benchmark-from-msgpack-lite.ts
src/CachedKeyDecoder.ts
src/Decoder.ts
src/Encoder.ts
src/decode.ts
src/decodeAsync.ts
src/encode.ts
test/reuse-instances.test.ts

It changes the interfaces to Encoder and Decoder,  so I'll bump the major version on the next release.
```
npx ts-node benchmark/benchmark-from-msgpack-lite.ts
Benchmark on NodeJS/v14.8.0 (V8/8.4)
operation                                                         |   op   |   ms  |  op/s
----------------------------------------------------------------- | ------: | ----: | ------:
buf = Buffer.from(JSON.stringify(obj));                           |  763800 |  5000 |  152760
buf = JSON.stringify(obj);                                        | 1086600 |  5000 |  217320
obj = JSON.parse(buf);                                            | 1634600 |  5000 |  326920
buf = require("msgpack-lite").encode(obj);                        |  462900 |  5000 |   92580
obj = …
```

make Encoder/Decoder instances easily reusable

---

README.md

Looks like there is a typo in the examples for `decodeArrayStream` and `decodeStream`, they both import `encode`.

Fix import typo in README

---

example/fetch-example-server.ts
example/fetch-example.html

As suggested in README.md, `await decodeAsync(response.body)` is recommended, but also `decode(await response.arrayBuffer())` is available.
#124

add fetch-example

---

README.md

* removed duplicated import statement
* fixed invalid assignment statement
BTW, when I tries to run the example code for working with extension type, I have faced the following tsc compile error.
```
error TS2322: Type 'ExtensionCodec<MyContext>' is not assignable to type 'ExtensionCodecType<undefined>'.
Types of property '__brand' are incompatible.
Type 'MyContext' is not assignable to type 'undefined'.
```
I'm investigating the issue it right now. If there'll be something worth to be considered, I'll suggest another PR or raise up an issue.

chore: invalid syntax in the example code

---

README.md

recommend enabling `strict` mode for avoiding type checking failure when using this library in TypeScript project.
As I mentioned in https://github.com/msgpack/msgpack-javascript/pull/135 , I found the circumstance where the type checking for encode/decode function call fails.
That specifically happens when user defined context type is given to the ExtensionCodec.
```
const extensionCodec = new ExtensionCodec<UserDefinedContext>();
```
Set `compilerOptions.strictNullChecks` to `true` in `tsconfig.json`. 
I'm not so familiar with TypeScript and still don't understand why this issue happens. (I'll follow up this phenomenon for my interest later)

[suggestion] chore: add annotation typescript usage in README

---

.gitignore
package.json
src/index.ts
tools/esmify.ts
tsconfig.dist.es5+esm.json
webpack.config.ts

Provides ES modules by setting "module" field in package.json

---

README.md
example/webpack-example/.gitignore
example/webpack-example/README.md
example/webpack-example/index.ts
example/webpack-example/package.json
example/webpack-example/tsconfig.json
example/webpack-example/webpack.config.ts
package.json

Webpack uses `browser` field in package.json as first, so it should be removed for ESM-based tree shaking.
https://webpack.js.org/configuration/resolve/

Tree Shakable package

---

src/context.ts
src/decode.ts
src/decodeAsync.ts
src/encode.ts

This PR intends to fix the issue reported on #136 , where I described the workaround for avoiding type check error in TypeScript.
The goal of this PR is making msgpack-javascript available from TypeScript both with/without enabling `strictNullCheck` compile option.
Since I don't know the actual intention of the original implementer ( @grantila ),  the change in this PR might be controversial.
So, though it would be appreciated if you welcome this PR, I highly recommend to ask @grantila 's opinion.
https://github.com/msgpack/msgpack-javascript/blob/8ba75f85cc45048dc8b7ab7dad623740dcc3a656/src/context.ts#L3
I think this implementation has some issues.
[This short code](https://www.typescriptlang.org/play?strictNullChecks=false#code/PTAEHUAsFMDtQM4BcBOBLAxkgcgVwDb4DCMGA1qGgqACZUCGARvtDQFBtICe …

[proposal] fix: type check issues on encod/decode arguments

---

README.md
src/Decoder.ts
src/decode.ts
src/decodeAsync.ts
test/decodeAsync.test.ts

`BufferSource` is defined as `ArrayBuffer | ArrayBufferView` in TypeScript.
cf. https://github.com/msgpack/msgpack-javascript/issues/152#issuecomment-778712021
cc: @prajaybasu

fix: make decodeAsync(), decodeStream(), and decodeArrayStream() to take BufferSource

---

README.md
src/Decoder.ts
src/decode.ts
src/decodeAsync.ts
src/index.ts
test/decodeMulti.test.ts
test/decodeMultiStream.test.ts

* introduce `decodeMulti()` to resolve #152
* introduce `decodeMultiStream()`, which is a new name for `decodeStream()`
* deprecate `decodeStream()` in favor of `decodeMultiStream()`
close #152

introduce decodeMulti()

---

src/Decoder.ts
test/prototype-pollution.test.ts

Injecting `__proto__` is a kind of the prototype pollution, although it's difficult to exploit.

reject __proto__ since it could break the object

---

src/Decoder.ts
src/Encoder.ts
test/edge-cases.test.ts

Decoder's state breaks if it tries to decode broken inputs, and there's no way to recover. This PR resets the state in initialization. 
This will mitigate #160.

reset Decoder's state to recover from broken input

---

src/utils/utf8.ts

Alternative to https://github.com/msgpack/msgpack-javascript/pull/199

Handle the case where process.env does not exists (but process exists)

---

.github/workflows/codeql.yml

This is required when "Workflow permissions" is set to "Read repository contents permission":
As its README describes: https://github.com/github/codeql-action#usage

[CI] set security-events: write for CodeQL workflow

---

.eslintrc.js
.vscode/settings.json
package-lock.json
package.json
src/Decoder.ts
src/decode.ts
src/decodeAsync.ts
test/edge-cases.test.ts

As `JSON.parse("")` raises a SyntaxError, `msgpack.decode([])` raises a RangeError. In fact, it always raises RangeError if the input is insufficient.
resolve #198

[doc] clarify the edge cases where the input buffer is empty

---

.github/workflows/ci.yml
.github/workflows/fuzz.yml
CHANGELOG.md
package.json
src/Encoder.ts
src/encode.ts
test/reuse-instances.test.ts

This is an intentional behavior but I'll change it because it's confusing. 
See #212 and the added tests for details.

fix #212; Let Encoder#encode() return a copy of the internal buffer

---

src/Decoder.ts
test/edge-cases.test.ts

Rationale: https://github.com/tc39/proposal-type-annotations#omitted-typescript-specific-features-that-generate-code
The `tc39/proposal-type-annotations` is considered a minimum viable subset of the TypeScript language. It would be nicer if TypeScript libraries can follow the spec so that any TypeScript processors can compile them.

avoid using typescript-specific language extensions (const enum)

---

CHANGELOG.md
README.md
src/Decoder.ts
src/Encoder.ts
src/decode.ts
src/decodeAsync.ts
src/encode.ts
src/index.ts
test/decode-max-length.test.ts

This is a major interface change even if the interfaces of Encoder and Decoder were not described in README.

let Encoder and Decoder accept named params as encode() and decode() do

---

README.md

Fixes example so data doesn't get lost in recursion.
Creates valid workaround for #138
Spent about a hour before I realized the example was broken. 🤦‍♀️

Fix ExtensionCodec example so it recurses.

---

src/Decoder.ts

hey @gfx found optimisation that I've missed somehow 2 years ago :D 
StackStates are constantly being created for each array or map parsed. 
If for example we parse array with 10k objects inside, it will allocate 10001 stack states, but in reality we only need 2 allocations. Max amount of allocation equals the max depth of nested objects/arrays inside on payload.
I've run msgpack benchmark, but it didn't show any large improvements. But I think these tests can't show it because they are very short living and GC have no time to kick off. 
Change is simple and can have meaningful impact of apps processing large amount of data.
Also unified stack state object creation with fields from both types created in one place should have impact on V8 optimisation pipeline, because now each object will …

Reuse stack states during decoding to optimize GC load

---

benchmark/msgpack-benchmark.js
src/Encoder.ts
src/ExtData.ts
src/ExtensionCodec.ts
test/ExtensionCodec.test.ts

An alternative solution for the data alignment proposed in that [PR](https://github.com/msgpack/msgpack-javascript/pull/245)
In that proposal, the `encode` function of the extension codec could return a function that will be called by `Encoder` at the moment of building the final buffer. The function receives the position of the data in the buffer. The encoder expects to receive data that will be then added to the buffer at the provided position. Users can add the padding bytes straight into the data at the encoding phase and calculate the data offset at the decoding phase depending on the chosen padding+data format.
That solution has some advantages over the one mentioned above. 
- It doesn't change the message pack format. The padding "lives" in the data part.
- It allows a user to …

Allow the data alignment to support zero-copy decoding

---

src/Decoder.ts
src/Encoder.ts
test/reuse-instances-with-extensions.test.ts
tsconfig.dist.es5+esm.json

close #195
```
$ npx mocha test/reuse-instances-with-extensions.test.ts
reuse instances with extensions
1) should encode and decode a bigint
0 passing (5ms)
1 failing
1) reuse instances with extensions
should encode and decode a bigint:
RangeError: Extra 6 of 9 byte(s) found at buffer[3]
at Decoder.createExtraByteError (src/Decoder.ts:274:12)
at Decoder.decode (src/Decoder.ts:287:18)
at Context.<anonymous> (test/reuse-instances-with-extensions.test.ts:38:26)
at processImmediate (node:internal/timers:491:21)
```

add a regression test based on #195

---

README.md
src/Decoder.ts
test/decodeAsync.test.ts

Adding support for nonstandard map key in the decoder by adding a new callback function in the decoder options that accepts the decoded map key and returns a JS standard map key (string or number)
fix #255

adding support for nonstandard map key in the decoder
